title: "Building Websites in GitHub"
description: "This research project develops training materials for researchers wanting to learn to build project websites in GitHub with GitHub Pages."
email: "team@carpentries.org"
twitter.handle: '\@AndruRomanowski'
twitter: "https://twitter.com/AndruRomanowski"
